### ISSUE TITLE
(우선순위 중/난이도 하) 2P의 발사되는 고기 크기 조절

### ISSUE THREAD

**Issue by EQwon** [SNUGDC/CatDefense#1]
1. 화살표로 조준할 때 고기의 크기가 1/5로 축소되어 있음.
    -> Parent인 'rac'의 크기가 1/5이라서 그런것 같습니다.
2. 스페이스를 눌러 발사 했을 때의 고기의 크기도 1/5로 축소되어 있음.
    -> Prefab에 있는 'meat'를 수정하면 될 것 같습니다.

**Comment by majecty** [comment]
Fixed by @EQwon
